spring.main.allow-bean-definition-overriding=true
spring.application.name=sample-spring-ai-2

# Set your OpenAI API key
spring.ai.openai.api-key=${OPENAI_API_KEY:Add key here }

spring.ai.openai.chat.options.model=gpt-4o-mini

# Print the outgoing prompt & incoming completion in console
logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.web.client.RestClient=DEBUG
logging.level.org.apache.hc.client5.http=DEBUG

# db connectivity
spring.sql.init.mode=always
#
# Server port
server.port=8081

# PostgreSQL Connection pointing to core_banking_db and app_core schema
spring.datasource.url=jdbc:postgresql://localhost:5432/core_banking_db?currentSchema=app_core
spring.datasource.username=app_runtime_user
spring.datasource.password=Add Password Here
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate configuration
spring.jpa.properties.hibernate.default_schema=app_core
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# HikariCP Connection Pool
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5


# Set the Swagger UI endpoint to /docs
springdoc.swagger-ui.path=/docs

# Set the OpenAPI JSON specification endpoint
springdoc.api-docs.path=/v3/api-docs

# Enable operations sorter and keep documentation ordered
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha